testData = {u'name': u'Michels Office',
 u'roomDeviceLabels': [u'Aeon SmartStrip 03',
                       u'Aeon Ss 01',
                       u'Aeon Ss 02',
                       u'SmartSense Motion/Temp Sensor 01'],
 u'roomDevices': [{u'children': {u'device': {u'id': u'db91bd2b-b03e-40e5-9889-7fa74107c262',
                                             u'label': u'Aeon SmartStrip 03',
                                             u'name': u'Aeon SmartStrip'},
                                 u'energy': {u'childenergy': 0.009999999776482582,
                                             u'energy1State': u'0E+1',
                                             u'energy2State': u'0.01',
                                             u'energy3State': u'0E+1',
                                             u'energy4State': u'0E+1',
                                             u'energyState': u'0.05',
                                             u'nonmonitoredEnergy': u'0.05'},
                                 u'power': {u'childPower': 0,
                                            u'nonmonitorPower': u'',
                                            u'power1State': u'0',
                                            u'power2State': u'0',
                                            u'power3State': u'0',
                                            u'power4State': u'0',
                                            u'powerState': u'0'},
                                 u'switches': {u'switch1State': u'on',
                                               u'switch2State': u'on',
                                               u'switch3State': u'on',
                                               u'switch4State': u'on',
                                               u'switchState': u'on'}},
                   u'device': {u'id': u'db91bd2b-b03e-40e5-9889-7fa74107c262',
                               u'label': u'Aeon SmartStrip 03',
                               u'name': u'Aeon SmartStrip'},
                   u'label': u'Aeon SmartStrip 03'},
                  {u'children': {u'device': {u'id': u'db91bd2b-b03e-40e5-9889-7fa74107c262',
                                             u'label': u'Aeon SmartStrip 03',
                                             u'name': u'Aeon SmartStrip'},
                                 u'energy': {u'childenergy': 0.009999999776482582,
                                             u'energy1State': u'0E+1',
                                             u'energy2State': u'0.01',
                                             u'energy3State': u'0E+1',
                                             u'energy4State': u'0E+1',
                                             u'energyState': u'0.05',
                                             u'nonmonitoredEnergy': u'0.05'},
                                 u'power': {u'childPower': 0,
                                            u'nonmonitorPower': u'',
                                            u'power1State': u'0',
                                            u'power2State': u'0',
                                            u'power3State': u'0',
                                            u'power4State': u'0',
                                            u'powerState': u'0'},
                                 u'switches': {u'switch1State': u'on',
                                               u'switch2State': u'on',
                                               u'switch3State': u'on',
                                               u'switch4State': u'on',
                                               u'switchState': u'on'}},
                   u'device': {u'id': u'db91bd2b-b03e-40e5-9889-7fa74107c262',
                               u'label': u'Aeon SmartStrip 03',
                               u'name': u'Aeon SmartStrip'},
                   u'label': u'Aeon SmartStrip 03'},
                  {u'children': {u'device': {u'id': u'abe801ad-b07e-4bcc-9b8c-b26bae2cb099',
                                             u'label': u'Aeon Ss 01',
                                             u'name': u'Aeon SmartStrip'},
                                 u'energy': {u'childenergy': 149.73000144958496,
                                             u'energy1State': u'51.31',
                                             u'energy2State': u'17.49',
                                             u'energy3State': u'27.7',
                                             u'energy4State': u'53.23',
                                             u'energyState': u'236.32',
                                             u'nonmonitoredEnergy': u'236.32'},
                                 u'power': {u'childPower': 258,
                                            u'nonmonitorPower': u'256',
                                            u'power1State': u'119',
                                            u'power2State': u'17',
                                            u'power3State': u'40',
                                            u'power4State': u'82',
                                            u'powerState': u'256'},
                                 u'switches': {u'switch1State': u'on',
                                               u'switch2State': u'on',
                                               u'switch3State': u'on',
                                               u'switch4State': u'on',
                                               u'switchState': u'on'}},
                   u'device': {u'id': u'abe801ad-b07e-4bcc-9b8c-b26bae2cb099',
                               u'label': u'Aeon Ss 01',
                               u'name': u'Aeon SmartStrip'},
                   u'label': u'Aeon Ss 01'},
                  {u'children': {u'device': {u'id': u'abe801ad-b07e-4bcc-9b8c-b26bae2cb099',
                                             u'label': u'Aeon Ss 01',
                                             u'name': u'Aeon SmartStrip'},
                                 u'energy': {u'childenergy': 149.73000144958496,
                                             u'energy1State': u'51.31',
                                             u'energy2State': u'17.49',
                                             u'energy3State': u'27.7',
                                             u'energy4State': u'53.23',
                                             u'energyState': u'236.32',
                                             u'nonmonitoredEnergy': u'236.32'},
                                 u'power': {u'childPower': 258,
                                            u'nonmonitorPower': u'256',
                                            u'power1State': u'119',
                                            u'power2State': u'17',
                                            u'power3State': u'40',
                                            u'power4State': u'82',
                                            u'powerState': u'256'},
                                 u'switches': {u'switch1State': u'on',
                                               u'switch2State': u'on',
                                               u'switch3State': u'on',
                                               u'switch4State': u'on',
                                               u'switchState': u'on'}},
                   u'device': {u'id': u'abe801ad-b07e-4bcc-9b8c-b26bae2cb099',
                               u'label': u'Aeon Ss 01',
                               u'name': u'Aeon SmartStrip'},
                   u'label': u'Aeon Ss 01'},
                  {u'children': {u'device': {u'id': u'a7243303-371a-499c-b0b6-d35e1813fb27',
                                             u'label': u'Aeon Ss 02',
                                             u'name': u'Aeon SmartStrip'},
                                 u'energy': {u'childenergy': 1577.209995150566,
                                             u'energy1State': u'2.74',
                                             u'energy2State': u'0.79',
                                             u'energy3State': u'0.56',
                                             u'energy4State': u'1573.12',
                                             u'energyState': u'1612.11',
                                             u'nonmonitoredEnergy': u'1612.11'},
                                 u'power': {u'childPower': 4,
                                            u'nonmonitorPower': u'3',
                                            u'power1State': u'0',
                                            u'power2State': u'4',
                                            u'power3State': u'0',
                                            u'power4State': u'0',
                                            u'powerState': u'43'},
                                 u'switches': {u'switch1State': u'on',
                                               u'switch2State': u'on',
                                               u'switch3State': u'on',
                                               u'switch4State': u'on',
                                               u'switchState': u'on'}},
                   u'device': {u'id': u'a7243303-371a-499c-b0b6-d35e1813fb27',
                               u'label': u'Aeon Ss 02',
                               u'name': u'Aeon SmartStrip'},
                   u'label': u'Aeon Ss 02'},
                  {u'children': {u'device': {u'id': u'a7243303-371a-499c-b0b6-d35e1813fb27',
                                             u'label': u'Aeon Ss 02',
                                             u'name': u'Aeon SmartStrip'},
                                 u'energy': {u'childenergy': 1577.209995150566,
                                             u'energy1State': u'2.74',
                                             u'energy2State': u'0.79',
                                             u'energy3State': u'0.56',
                                             u'energy4State': u'1573.12',
                                             u'energyState': u'1612.11',
                                             u'nonmonitoredEnergy': u'1612.11'},
                                 u'power': {u'childPower': 4,
                                            u'nonmonitorPower': u'3',
                                            u'power1State': u'0',
                                            u'power2State': u'4',
                                            u'power3State': u'0',
                                            u'power4State': u'0',
                                            u'powerState': u'43'},
                                 u'switches': {u'switch1State': u'on',
                                               u'switch2State': u'on',
                                               u'switch3State': u'on',
                                               u'switch4State': u'on',
                                               u'switchState': u'on'}},
                   u'device': {u'id': u'a7243303-371a-499c-b0b6-d35e1813fb27',
                               u'label': u'Aeon Ss 02',
                               u'name': u'Aeon SmartStrip'},
                   u'label': u'Aeon Ss 02'},
                  {u'children': {u'battery': {u'date': u'2015-07-30T15:22:55.535Z',
                                              u'name': u'battery',
                                              u'type': None,
                                              u'unit': None,
                                              u'unixTime': 1438269775535,
                                              u'value': u'77'},
                                 u'device': {u'id': u'a256e80e-f415-437b-bf25-e381ea3ff7a9',
                                             u'label': u'SmartSense Motion/Temp Sensor 01',
                                             u'name': u'SmartSense Motion/Temp Sensor'},
                                 u'motion': {u'date': u'2015-09-17T17:28:24.034Z',
                                             u'name': u'motion',
                                             u'type': None,
                                             u'unit': None,
                                             u'unixTime': 1442510904034,
                                             u'value': u'inactive'},
                                 u'temperature': {u'date': u'2015-09-17T14:39:39.101Z',
                                                  u'name': u'temperature',
                                                  u'type': None,
                                                  u'unit': None,
                                                  u'unixTime': 1442500779101,
                                                  u'value': u'71'}},
                   u'device': {u'id': u'a256e80e-f415-437b-bf25-e381ea3ff7a9',
                               u'label': u'SmartSense Motion/Temp Sensor 01',
                               u'name': u'SmartSense Motion/Temp Sensor'},
                   u'label': u'SmartSense Motion/Temp Sensor 01'}]}
